### ISSUE TITLE
Proprietary

### ISSUE THREAD

**Issue by sevgajuk** [ti-bone/cas-moderator-bot-issue-tracker#1]
"-" rep
"+" backdoors

**Comment by ti-bone** [comment]
"+" 4 Furry for You)

**Comment by PyJSBiba** [comment]
BACKDOOR DELETED, EBANNII ROT YDALEN, XYI PIZDA SCOVORODA DEINSTALIZIROVANI IS SYSTEMI, SPASIBO SEVGADCHUKU

**Comment by sevgajuk** [comment]
Bruh
