### ISSUE TITLE
Proprietary!

### ISSUE THREAD

**Issue by sevgajuk** [ti-bone/cas-moderator-bot-issue-tracker#2]
"-" rep
"+" backdoors!!!

Big brother is watching you.

**Comment by PyJSBiba** [comment]
ЭЛДЬЩПКУЛЬЩШЛЗОЬЩП4ДЗЛЩХЬБПОЛЬЩ-ПК5ШЛЬЗХЕМИ ТШ0ПУК43МИ ЗШЩОТ9УАЗГО4ЩТМП ЬВИКАШЩОТ УЦАСМЦВ ЫСШЩОТУАМЦПШЩВЗГ ОСЛТЧЬМЩ9ЗОЛТМВЬ СЧШГРТОЛФУЫВМЬ АСТЩШИДЛОЬ уцсамвсшщ0жзгртоьи вукащшжлдьтмуцви щшослдьб

**Comment by ti-bone** [comment]
Duplicate of #1

**Comment by PyJSBiba** [comment]
ШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАКШЁПОЛ ХАНУЙ БУЁБАК
